### ISSUE TITLE
not work in almalinux 9.5

### ISSUE THREAD

**Issue by habnai** [xiahualiu/wg_gaming_installer#30]
i get this error: 
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://repo.almalinux.org/almalinux/RPM-GPG-KEY-AlmaLinux: key 1 import failed.
No match for argument: kmod-wireguard
No match for argument: wireguard-tools
No match for argument: qrencode
No packages marked for removal.
Dependencies resolved.
Nothing to do.

**Comment by xiahualiu** [comment]
I think this is because AlmaLinux 9.5 is too new, I haven't test it myself but will test is in VM next.

You can play with https://github.com/xiahualiu/wg_gaming_installer/blob/main/install.sh#L107-L112 and see if anything wrong with it. I don't know but it seems the OS is too new so many packages are missing now.

**Comment by xiahualiu** [comment]
I have made a fix for this issue. Can you try #31 branch to see if it works?

```bash
git clone https://github.com/xiahualiu/wg_gaming_installer.git
cd ./wg_gaming_installer
git switch issue_30
./install.sh
```

**Comment by habnai** [comment]
Thank you for your fix.
installed without problem.
